$ErrorActionPreference = "Stop"

$sourceDir = Join-Path $PSScriptRoot "Source Code"
$moduleDir = Join-Path $sourceDir "ruby_modules"
$outputPath = Join-Path $sourceDir "god_mode_source.rb"

$moduleOrder = @(
    "00_header.rb",
    "10_core_01_runtime.rb",
    "10_core_02_engine_player.rb",
    "10_core_03_pokemon.rb",
    "10_core_04_stats_items.rb",
    "10_core_05_battles_world.rb",
    "10_core_06_search_ui.rb",
    "11_input_and_mobile.rb",
    "12_menu_helpers.rb",
    "13_status_and_summaries.rb",
    "14_engine_profile.rb",
    "15_battle_access.rb",
    "16_reports_and_extras.rb",
    "17_engine_adapters.rb",
    "18_pokedebug_device.rb",
    "20_engine.rb",
    "30_pokemon_items_player.rb",
    "40_party.rb",
    "45_battle_tools.rb",
    "50_runtime_patches.rb"
)

$missing = $moduleOrder | Where-Object {
    -not (Test-Path (Join-Path $moduleDir $_) -PathType Leaf)
}
if ($missing) {
    throw "Missing ruby module files: $($missing -join ', ')"
}

$banner = @(
    "# This file is generated by Generate-GodModeSource.ps1.",
    "# Edit the files in Source Code\\ruby_modules instead of editing this file directly.",
    ""
)

$content = New-Object System.Collections.Generic.List[string]
$banner | ForEach-Object { [void]$content.Add($_) }

foreach ($moduleName in $moduleOrder) {
    $modulePath = Join-Path $moduleDir $moduleName
    [void]$content.Add("# --- BEGIN $moduleName ---")
    Get-Content -LiteralPath $modulePath | ForEach-Object { [void]$content.Add($_) }
    [void]$content.Add("# --- END $moduleName ---")
    [void]$content.Add("")
}

Set-Content -LiteralPath $outputPath -Value $content -Encoding UTF8
Write-Host "[OK] Generated Source Code\\god_mode_source.rb from ruby_modules." -ForegroundColor Green
