$ErrorActionPreference = "Stop"

$sourceDir = Join-Path $PSScriptRoot "Source Code"
$moduleDir = Join-Path $sourceDir "ruby_modules"
$outputPath = Join-Path $sourceDir "god_mode_source.rb"

$moduleOrder = @(
    "00_header.rb",
    "10_core.rb",
    "20_engine.rb",
    "30_pokemon_items_player.rb",
    "40_party.rb",
    "50_runtime_patches.rb"
)

$missing = $moduleOrder | Where-Object { -not (Test-Path (Join-Path $moduleDir $_) -PathType Leaf) }
if ($missing) {
    throw "Missing ruby module files: $($missing -join ', ')"
}

$banner = @(
    "# This file is generated by Generate-GodModeSource.ps1.",
    "# Edit the files in Source Code\\ruby_modules instead of editing this file directly.",
    ""
)

$content = New-Object System.Collections.Generic.List[string]
$banner | ForEach-Object { [void]$content.Add($_) }

foreach ($moduleName in $moduleOrder) {
    $modulePath = Join-Path $moduleDir $moduleName
    [void]$content.Add("# --- BEGIN $moduleName ---")
    Get-Content $modulePath | ForEach-Object { [void]$content.Add($_) }
    [void]$content.Add("# --- END $moduleName ---")
    [void]$content.Add("")
}

Set-Content -Path $outputPath -Value $content -Encoding UTF8
Write-Host "[OK] Generated Source Code\\god_mode_source.rb from ruby_modules." -ForegroundColor Green
