#===============================================================================
# PokeDebug Menu Created by: Kzuran/Erdeem
# https://github.com/Erdeem/
# Please do not redistribute this script without giving credits.
#===============================================================================
# This script is a plugin that makes the menu, the plugin is loaded by preload_gm.rb.
# It allows you to manipulate various aspects of the game, such as Pokemon,
# items, money, badges, and more. It also provides quick access to certain
# features like warping to maps, toggling battle settings, and editing PBS files.
#===============================================================================
module DeveloperMenu
  VERSION = '3.1.0'
  LOG_FILE_NAME = 'developer_menu_errors.log'
  STATE_FILE_NAME = 'developer_menu_boot_state.dat'
  LANG = 'en'
  LANG_KEYS = {
    "en" => "English",
    "pt" => "Portugues",
    "es" => "Espanol"
  }
  MENU_HOTKEY = 'F6'
  WTW_HOTKEY = 'F5'
  HEAL_HOTKEY = 'F9'
  TR = {
    :dev_menu => {"English" => "PokeDebug Menu", "Portugues" => "PokeDebug Menu", "Espanol" => "PokeDebug Menu"},
    :engine => {"English" => "Engine", "Portugues" => "Engine do Jogo", "Espanol" => "Motor del Juego"},
    :pokemon => {"English" => "Pokemon", "Portugues" => "Pokemon", "Espanol" => "Pokemon"},
    :items => {"English" => "Items", "Portugues" => "Itens", "Espanol" => "Objetos"},
    :Player => {"English" => "Player", "Portugues" => "Jogador", "Espanol" => "Jugador"},
    :party => {"English" => "Party", "Portugues" => "Equipe", "Espanol" => "Equipo"},
    :extras => {"English" => "Extras", "Portugues" => "Extras", "Espanol" => "Extras"},
    :back => {"English" => "Back/Cancel", "Portugues" => "Voltar / Cancelar", "Espanol" => "Volver / Cancelar"},
    
    :warp => {"English" => "Warp to Map", "Portugues" => "Ir para Mapa", "Espanol" => "Ir al Mapa"},
    :switches => {"English" => "Switches", "Portugues" => "Interruptores", "Espanol" => "Interruptores"},
    :vars => {"English" => "Variables", "Portugues" => "Variaveis", "Espanol" => "Variables"},
    :safari => {"English" => "Safari / Contest", "Portugues" => "Safari / Torneio", "Espanol" => "Safari / Torneo"},
    :Field => {"English" => "Field Effects", "Portugues" => "Efeitos de Campo", "Espanol" => "Efectos de Campo"},
    :refresh => {"English" => "Refresh Map", "Portugues" => "Atualizar Mapa", "Espanol" => "Actualizar Mapa"},
    :daycare => {"English" => "Day Care", "Portugues" => "Creche (Day Care)", "Espanol" => "Guarderia"},
    :Wallpapers => {"English" => "Toggle PC Wallpapers", "Portugues" => "Alternar Wallpapers do PC", "Espanol" => "Alternar Fondos de PC"},
    :Battle => {"English" => "Test Wild Battle", "Portugues" => "Testar Batalha Selvagem", "Espanol" => "Probar Batalla Salvaje"},
    :battle_advanced => {"English" => "Test Wild Battle Advanced", "Portugues" => "Testar Batalha Selvagem Avancada", "Espanol" => "Probar Batalla Salvaje Avanzada"},
    :expall => {"English" => "Toggle Exp. All", "Portugues" => "Alternar Exp. All", "Espanol" => "Alternar Exp. All"},
    :wtw => {"English" => "Toggle Walk Through Walls", "Portugues" => "Atravessar Paredes", "Espanol" => "Atravesar Paredes"},
    :openpc => {"English" => "Open PC", "Portugues" => "Abrir PC", "Espanol" => "Abrir PC"},
    :runtime_debug_toggle => {"English" => "Turn Debug ON/OFF", "Portugues" => "Ligar/Desligar Debug", "Espanol" => "Activar/Desactivar Debug"},
    :pbs_editors => {"English" => "PBS Editors", "Portugues" => "Editores PBS", "Espanol" => "Editores PBS"},
    :pbs_map_connections => {"English" => "Edit map_connections.txt", "Portugues" => "Editar map_connections.txt", "Espanol" => "Editar map_connections.txt"},
    :pbs_encounters => {"English" => "Edit encounters.txt", "Portugues" => "Editar encounters.txt", "Espanol" => "Editar encounters.txt"},
    :pbs_trainers => {"English" => "Edit trainers.txt", "Portugues" => "Editar trainers.txt", "Espanol" => "Editar trainers.txt"},
    :pbs_trainer_types => {"English" => "Edit trainer_types.txt", "Portugues" => "Editar trainer_types.txt", "Espanol" => "Editar trainer_types.txt"},
    :pbs_map_metadata => {"English" => "Edit map_metadata.txt", "Portugues" => "Editar map_metadata.txt", "Espanol" => "Editar map_metadata.txt"},
    :pbs_metadata => {"English" => "Edit metadata.txt", "Portugues" => "Editar metadata.txt", "Espanol" => "Editar metadata.txt"},
    :pbs_items => {"English" => "Edit items.txt", "Portugues" => "Editar items.txt", "Espanol" => "Editar items.txt"},
    :pbs_species => {"English" => "Edit pokemon.txt", "Portugues" => "Editar pokemon.txt", "Espanol" => "Editar pokemon.txt"},
    :pbs_regional_dexes => {"English" => "Edit regional_dexes.txt", "Portugues" => "Editar regional_dexes.txt", "Espanol" => "Editar regional_dexes.txt"},
    :encounter_version => {"English" => "Set Wild Encounters Version", "Portugues" => "Definir Versao dos Encontros", "Espanol" => "Definir Version de Encuentros"},
    :roaming_pokemon => {"English" => "Roaming Pokemon", "Portugues" => "Pokemon Errantes", "Espanol" => "Pokemon Errantes"},
    :reset_map_trainers => {"English" => "Reset Map's Trainers", "Portugues" => "Resetar Treinadores do Mapa", "Espanol" => "Reiniciar Entrenadores del Mapa"},
    :battle_logging => {"English" => "Toggle Battle Logging", "Portugues" => "Alternar Log de Batalha", "Espanol" => "Alternar Registro de Batalla"},
    :skip_credits => {"English" => "Skip Credits", "Portugues" => "Pular Creditos", "Espanol" => "Saltar Creditos"},
    
    :FillPC => {"English" => "Fill PC Boxes", "Portugues" => "Encher Caixas do PC", "Espanol" => "Llenar Cajas del PC"},
    :ClearPC => {"English" => "Clear PC Boxes", "Portugues" => "Limpar Caixas do PC", "Espanol" => "Vaciar Cajas del PC"},
    :addboxes => {"English" => "Add PC Boxes", "Portugues" => "Adicionar Caixas ao PC", "Espanol" => "Anadir Cajas al PC"},
    :quickhatch => {"English" => "Quick Hatch Party Eggs", "Portugues" => "Chocar Ovos Rapidamente", "Espanol" => "Eclosionar Huevos Rapidamente"},
    :addpkmn => {"English" => "Add Pokemon", "Portugues" => "Adicionar Pokemon", "Espanol" => "Anadir Pokemon"},
    :Heal => {"English" => "Heal Party", "Portugues" => "Curar Equipe", "Espanol" => "Curar Equipo"},
    :exportids => {"English" => "Export Species IDs", "Portugues" => "Exportar IDs", "Espanol" => "Exportar IDs"},
    
    :additem => {"English" => "Add Item", "Portugues" => "Adicionar Item", "Espanol" => "Anadir Objeto"},
    :fillbag => {"English" => "Fill Bag (All)", "Portugues" => "Encher Mochila (Tudo)", "Espanol" => "Llenar Mochila (Todo)"},
    :fillbagnon => {"English" => "Fill Bag (Non-Key)", "Portugues" => "Encher Mochila (Sem Itens Chave)", "Espanol" => "Llenar Mochila (Sin Objetos Clave)"},
    :fillbagkey => {"English" => "Fill Bag (Key Items)", "Portugues" => "Encher Mochila (So Itens Chave)", "Espanol" => "Llenar Mochila (Solo Clave)"},
    :emptybag => {"English" => "Empty Bag", "Portugues" => "Esvaziar Mochila", "Espanol" => "Vaciar Mochila"},
    
    :money => {"English" => "Edit Money", "Portugues" => "Editar Dinheiro", "Espanol" => "Editar Dinero"},
    :coins => {"English" => "Edit Coins", "Portugues" => "Editar Moedas", "Espanol" => "Editar Monedas"},
    :bp => {"English" => "Edit Battle Points", "Portugues" => "Editar BP", "Espanol" => "Editar BP"},
    :badges => {"English" => "Toggle All Badges", "Portugues" => "Alternar Todas as Insignias", "Espanol" => "Alternar Todas las Medallas"},
    :pokedex => {"English" => "Complete Pokedex", "Portugues" => "Completar Pokedex", "Espanol" => "Completar Pokedex"},
    :fly => {"English" => "Unlock Fly Destinations", "Portugues" => "Desbloquear Voo (Fly)", "Espanol" => "Desbloquear Vuelo"},
    :name => {"English" => "Rename Player", "Portugues" => "Renomear Jogador", "Espanol" => "Renombrar Jugador"},
    :gender => {"English" => "Change Gender", "Portugues" => "Mudar Genero", "Espanol" => "Cambiar Genero"},
    :outfit => {"English" => "Change Outfit", "Portugues" => "Mudar Roupa", "Espanol" => "Cambiar Ropa"},
    :character => {"English" => "Player Character", "Portugues" => "Mudar Personagem", "Espanol" => "Cambiar Personaje"},
    :trainerid => {"English" => "Change Trainer ID", "Portugues" => "Mudar ID de Treinador", "Espanol" => "Cambiar ID"},
    :playtime => {"English" => "Edit Play Time", "Portugues" => "Editar Tempo de Jogo", "Espanol" => "Editar Tiempo Jugado"},
    :pokedex_tog => {"English" => "Toggle Pokedex", "Portugues" => "Alternar Pokedex", "Espanol" => "Alternar Pokedex"},
    :pokegear => {"English" => "Toggle Pokegear", "Portugues" => "Alternar Pokegear", "Espanol" => "Alternar Pokegear"},
    :shoes => {"English" => "Toggle Running Shoes", "Portugues" => "Alternar Tenis de Corrida", "Espanol" => "Alternar Zapatillas"},
    :ash => {"English" => "Edit Ash Count", "Portugues" => "Editar Cinzas (Ash)", "Espanol" => "Editar Cenizas"},
    :region => {"English" => "Change Region", "Portugues" => "Mudar Regiao", "Espanol" => "Cambiar Region"},
    :partner => {"English" => "Edit Partner", "Portugues" => "Gerenciar Parceiro", "Espanol" => "Gestionar Companero"},
    :phone_contacts => {"English" => "Edit Phone and Contacts", "Portugues" => "Editar Telefone e Contatos", "Espanol" => "Editar Telefono y Contactos"},
    :box_link => {"English" => "Toggle Box Link", "Portugues" => "Alternar Box Link", "Espanol" => "Alternar Box Link"},
    :randomize_player_id => {"English" => "Randomize Player ID", "Portugues" => "Randomizar ID do Jogador", "Espanol" => "Aleatorizar ID del Jugador"},
    :nobattles => {"English" => "Toggle No Battles", "Portugues" => "Alternar Sem Batalhas", "Espanol" => "Alternar Sin Batallas"},
    :no_wild_battles => {"English" => "Toggle No Wild Battles", "Portugues" => "Alternar Sem Batalhas Selvagens", "Espanol" => "Alternar Sin Batallas Salvajes"},
    :no_trainer_battles => {"English" => "Toggle No Trainer Battles", "Portugues" => "Alternar Sem Batalhas de Treinador", "Espanol" => "Alternar Sin Batallas de Entrenador"},
    :infmega => {"English" => "Toggle Inf. Mega", "Portugues" => "Alternar Mega Evolucao Infinita", "Espanol" => "Alternar Mega Evolucion Infinita"},
    :nativedebug => {"English" => "Open Native Debug Menu", "Portugues" => "Abrir Debug Nativo", "Espanol" => "Abrir Debug Nativo"},
    :quick_actions => {"English" => "Quick Actions", "Portugues" => "Acoes Rapidas", "Espanol" => "Acciones Rapidas"},
    :configure_quick_actions => {"English" => "Configure Quick Actions", "Portugues" => "Configurar Acoes Rapidas", "Espanol" => "Configurar Acciones Rapidas"},
    :battle_access_settings => {"English" => "Battle Access Settings", "Portugues" => "Permissoes em Batalha", "Espanol" => "Permisos en Batalla"},
    :compatibility_report => {"English" => "Compatibility Report", "Portugues" => "Relatorio de Compatibilidade", "Espanol" => "Reporte de Compatibilidad"},
    :diagnostics_report => {"English" => "Diagnostics Report", "Portugues" => "Relatorio de Diagnostico", "Espanol" => "Reporte de Diagnostico"},
    :test_all => {"English" => "Test All", "Portugues" => "Testar Tudo", "Espanol" => "Probar Todo"},
    :configure_hotkeys => {"English" => "Configure Hotkeys", "Portugues" => "Configurar Atalhos", "Espanol" => "Configurar Atajos"},
    :engine_compatibility_report => {"English" => "Engine Compatibility Report", "Portugues" => "Relatorio da Engine", "Espanol" => "Reporte del Motor"},
    :mobile_open_help => {"English" => "Show JoiPlay/Mobile Open Help", "Portugues" => "Mostrar Ajuda para JoiPlay/Mobile", "Espanol" => "Mostrar Ayuda para JoiPlay/Mobile"},
    :custom_editor => {"English" => "Open Custom Pokemon Editor", "Portugues" => "Abrir Editor Custom de Pokemon", "Espanol" => "Abrir Editor Custom de Pokemon"},
    :native_editor => {"English" => "Open Native Pokemon Editor", "Portugues" => "Abrir Editor Nativo de Pokemon", "Espanol" => "Abrir Editor Nativo de Pokemon"},
    :empty_slot => {"English" => "Empty Slot", "Portugues" => "Slot Vazio", "Espanol" => "Espacio Vacio"},
    :refresh_map_short => {"English" => "Refresh Map", "Portugues" => "Atualizar Mapa", "Espanol" => "Actualizar Mapa"},
    :open_menu => {"English" => "Open Menu", "Portugues" => "Abrir Menu", "Espanol" => "Abrir Menu"},
    :heal_party_hotkey => {"English" => "Heal Party", "Portugues" => "Curar Equipe", "Espanol" => "Curar Equipo"},
    :wtw_hotkey => {"English" => "Walk Through Walls", "Portugues" => "Atravessar Paredes", "Espanol" => "Atravesar Paredes"},
    :hotkeys_reset => {"English" => "Hotkeys reset to default.", "Portugues" => "Hotkeys redefinidas para o padrao.", "Espanol" => "Hotkeys restablecidas al valor predeterminado."},
    :show_current_hotkeys => {"English" => "Show Current Hotkeys", "Portugues" => "Mostrar Hotkeys Atuais", "Espanol" => "Mostrar Hotkeys Actuales"},
    :reset_to_default => {"English" => "Reset to Default", "Portugues" => "Restaurar Padrao", "Espanol" => "Restaurar Predeterminado"},
    :choose_hotkey_for => {"English" => "Choose hotkey for {1}:", "Portugues" => "Escolha a hotkey para {1}:", "Espanol" => "Elige la hotkey para {1}:"},
    :quick_action_slot => {"English" => "Slot {1}: {2}", "Portugues" => "Slot {1}: {2}", "Espanol" => "Espacio {1}: {2}"},
    :choose_action_slot => {"English" => "Choose action for slot {1}:", "Portugues" => "Escolha a acao do slot {1}:", "Espanol" => "Elige la accion del espacio {1}:"},
    :no_quick_actions => {"English" => "No quick actions configured.", "Portugues" => "Nenhuma acao rapida configurada.", "Espanol" => "No hay acciones rapidas configuradas."},
    :mobile_help_text => {"English" => "JoiPlay/mobile fallback:\n- Hold L + R\n- Or hold AUX1 + AUX2 / X + Y\n- Extra fallback: hold L + A, R + B, or A + B + C\n- Current menu hotkey: {1}\n- Event/script call: pbPokeDebugMenu / pbPokeDebugMobileMenu", "Portugues" => "Fallback JoiPlay/mobile:\n- Segure L + R\n- Ou segure AUX1 + AUX2 / X + Y\n- Fallback extra: segure L + A, R + B ou A + B + C\n- Hotkey atual do menu: {1}\n- Chamada por evento/script: pbPokeDebugMenu / pbPokeDebugMobileMenu", "Espanol" => "Respaldo JoiPlay/mobile:\n- Mantén L + R\n- O mantén AUX1 + AUX2 / X + Y\n- Respaldo extra: mantén L + A, R + B o A + B + C\n- Hotkey actual del menu: {1}\n- Llamada por evento/script: pbPokeDebugMenu / pbPokeDebugMobileMenu"},
    :quick_status => {"English" => "Quick Status", "Portugues" => "Resumo Rapido", "Espanol" => "Resumen Rapido"},
    :import_preset => {"English" => "Import Pokemon Preset", "Portugues" => "Importar Preset de Pokemon", "Espanol" => "Importar Preset de Pokemon"},
    :map_event_tools => {"English" => "Map / Event Tools", "Portugues" => "Ferramentas de Mapa / Evento", "Espanol" => "Herramientas de Mapa / Evento"},
    :test_trainer_battle => {"English" => "Test Trainer Battle", "Portugues" => "Testar Batalha de Treinador", "Espanol" => "Probar Batalla de Entrenador"},
    :test_trainer_battle_advanced => {"English" => "Test Trainer Battle Advanced", "Portugues" => "Testar Batalha de Treinador Avancada", "Espanol" => "Probar Batalla de Entrenador Avanzada"},
    :edit_safari_contest => {"English" => "Edit Safari/Contest", "Portugues" => "Editar Safari/Torneio", "Espanol" => "Editar Safari/Torneo"},
    :field_effects_title => {"English" => "Field Effects", "Portugues" => "Efeitos de Campo", "Espanol" => "Efectos de Campo"},
    :wallpapers_title => {"English" => "Wallpapers", "Portugues" => "Wallpapers", "Espanol" => "Fondos"},
    :battle_tools_title => {"English" => "Battle Tools", "Portugues" => "Ferramentas de Batalha", "Espanol" => "Herramientas de Batalla"},
    :select_pokemon => {"English" => "Select Pokemon:", "Portugues" => "Selecionar Pokemon:", "Espanol" => "Seleccionar Pokemon:"},
    :hp_status => {"English" => "HP / Status", "Portugues" => "HP / Status", "Espanol" => "PS / Estado"},
    :level_stats => {"English" => "Level / Stats", "Portugues" => "Nivel / Atributos", "Espanol" => "Nivel / Atributos"},
    :moves_title => {"English" => "Moves", "Portugues" => "Movimentos", "Espanol" => "Movimientos"},
    :held_item => {"English" => "Held Item", "Portugues" => "Item Equipado", "Espanol" => "Objeto Equipado"},
    :ability_title => {"English" => "Ability", "Portugues" => "Habilidade", "Espanol" => "Habilidad"},
    :nature_gender => {"English" => "Nature & Gender", "Portugues" => "Natureza e Genero", "Espanol" => "Naturaleza y Genero"},
    :species_form => {"English" => "Species & Form", "Portugues" => "Especie e Forma", "Espanol" => "Especie y Forma"},
    :cosmetics_ribbons => {"English" => "Cosmetics & Ribbons", "Portugues" => "Cosmeticos e Fitas", "Espanol" => "Cosmeticos y Cintas"},
    :discardable_flags => {"English" => "Discardable Flags", "Portugues" => "Flags Restritivas", "Espanol" => "Flags Restrictivas"},
    :egg_options => {"English" => "Egg Options", "Portugues" => "Opcoes de Ovo", "Espanol" => "Opciones de Huevo"},
    :export_preset => {"English" => "Export Preset", "Portugues" => "Exportar Preset", "Espanol" => "Exportar Preset"},
    :apply_preset => {"English" => "Apply Preset", "Portugues" => "Aplicar Preset", "Espanol" => "Aplicar Preset"},
    :duplicate => {"English" => "Duplicate", "Portugues" => "Duplicar", "Espanol" => "Duplicar"},
    :delete_label => {"English" => "Delete", "Portugues" => "Excluir", "Espanol" => "Eliminar"},
    :edit_hp => {"English" => "Edit HP", "Portugues" => "Editar HP", "Espanol" => "Editar PS"},
    :faint => {"English" => "Faint", "Portugues" => "Desmaiar", "Espanol" => "Debilitar"},
    :status_problem => {"English" => "Status Problem", "Portugues" => "Problema de Status", "Espanol" => "Problema de Estado"},
    :clear_status => {"English" => "Clear Status", "Portugues" => "Limpar Status", "Espanol" => "Limpiar Estado"},
    :give_pokerus => {"English" => "Give Pokerus", "Portugues" => "Dar Pokerus", "Espanol" => "Dar Pokerus"},
    :cure_pokerus => {"English" => "Cure Pokerus", "Portugues" => "Curar Pokerus", "Espanol" => "Curar Pokerus"},
    :edit_level => {"English" => "Edit Level", "Portugues" => "Editar Nivel", "Espanol" => "Editar Nivel"},
    :edit_experience => {"English" => "Edit Experience", "Portugues" => "Editar Experiencia", "Espanol" => "Editar Experiencia"},
    :advanced_stat_editor => {"English" => "Advanced Stat Editor", "Portugues" => "Editor Avancado de Stats", "Espanol" => "Editor Avanzado de Stats"},
    :max_ivs => {"English" => "Max IVs", "Portugues" => "Maximizar IVs", "Espanol" => "Maximizar IVs"},
    :max_evs => {"English" => "Max EVs", "Portugues" => "Maximizar EVs", "Espanol" => "Maximizar EVs"},
    :edit_happiness => {"English" => "Edit Happiness", "Portugues" => "Editar Felicidade", "Espanol" => "Editar Felicidad"},
    :max_contest_stats => {"English" => "Max Contest Stats", "Portugues" => "Maximizar Stats de Concurso", "Espanol" => "Maximizar Stats de Concurso"},
    :randomize_personal_id => {"English" => "Randomize Personal ID", "Portugues" => "Randomizar Personal ID", "Espanol" => "Aleatorizar Personal ID"},
    :view_moveset => {"English" => "View Moveset", "Portugues" => "Ver Golpes", "Espanol" => "Ver Movimientos"},
    :learn_move => {"English" => "Learn Move", "Portugues" => "Aprender Golpe", "Espanol" => "Aprender Movimiento"},
    :forget_move => {"English" => "Forget Move", "Portugues" => "Esquecer Golpe", "Espanol" => "Olvidar Movimiento"},
    :reset_moveset => {"English" => "Reset Moveset", "Portugues" => "Resetar Golpes", "Espanol" => "Restablecer Movimientos"},
    :save_initial_moveset => {"English" => "Save Current as Initial Moveset", "Portugues" => "Salvar Atual como Moveset Inicial", "Espanol" => "Guardar Actual como Moveset Inicial"},
    :restore_pp => {"English" => "Restore PP", "Portugues" => "Restaurar PP", "Espanol" => "Restaurar PP"},
    :max_pp_ups => {"English" => "Max PP Ups", "Portugues" => "Maximizar PP Ups", "Espanol" => "Maximizar PP Ups"},
    :view_current_item => {"English" => "View Current Item", "Portugues" => "Ver Item Atual", "Espanol" => "Ver Objeto Actual"},
    :set_held_item => {"English" => "Set Held Item", "Portugues" => "Definir Item Segurado", "Espanol" => "Definir Objeto Equipado"},
    :remove_held_item => {"English" => "Remove Held Item", "Portugues" => "Remover Item Segurado", "Espanol" => "Quitar Objeto Equipado"},
    :view_current_ability => {"English" => "View Current Ability", "Portugues" => "Ver Habilidade Atual", "Espanol" => "Ver Habilidad Actual"},
    :set_legal_ability => {"English" => "Set Legal Ability", "Portugues" => "Definir Habilidade Valida", "Espanol" => "Definir Habilidad Valida"},
    :search_any_ability => {"English" => "Search Any Ability", "Portugues" => "Buscar Qualquer Habilidade", "Espanol" => "Buscar Cualquier Habilidad"},
    :reset_ability => {"English" => "Reset Ability", "Portugues" => "Resetar Habilidade", "Espanol" => "Restablecer Habilidad"},
    :export_ability_ids => {"English" => "Export Ability IDs", "Portugues" => "Exportar IDs de Habilidade", "Espanol" => "Exportar IDs de Habilidad"},
    :set_nature => {"English" => "Set Nature", "Portugues" => "Definir Natureza", "Espanol" => "Definir Naturaleza"},
    :set_legal_gender => {"English" => "Set Legal Gender", "Portugues" => "Definir Genero Valido", "Espanol" => "Definir Genero Valido"},
    :force_gender_male => {"English" => "Force Gender (Male)", "Portugues" => "Forcar Genero (Macho)", "Espanol" => "Forzar Genero (Macho)"},
    :force_gender_female => {"English" => "Force Gender (Female)", "Portugues" => "Forcar Genero (Femea)", "Espanol" => "Forzar Genero (Hembra)"},
    :force_gender_genderless => {"English" => "Force Gender (Genderless)", "Portugues" => "Forcar Genero (Sem Genero)", "Espanol" => "Forzar Genero (Sin Genero)"},
    :change_species => {"English" => "Change Species", "Portugues" => "Mudar Especie", "Espanol" => "Cambiar Especie"},
    :change_form => {"English" => "Change Form", "Portugues" => "Mudar Forma", "Espanol" => "Cambiar Forma"},
    :remove_form_override => {"English" => "Remove Form Override", "Portugues" => "Remover Override de Forma", "Espanol" => "Quitar Override de Forma"},
    :set_nickname => {"English" => "Set Nickname", "Portugues" => "Definir Apelido", "Espanol" => "Definir Apodo"},
    :toggle_shiny => {"English" => "Toggle Shiny", "Portugues" => "Alternar Shiny", "Espanol" => "Alternar Shiny"},
    :set_poke_ball => {"English" => "Set Poke Ball", "Portugues" => "Definir Poke Ball", "Espanol" => "Definir Poke Ball"},
    :add_ribbon => {"English" => "Add Ribbon", "Portugues" => "Adicionar Fita", "Espanol" => "Agregar Cinta"},
    :clear_all_ribbons => {"English" => "Clear All Ribbons", "Portugues" => "Remover Todas as Fitas", "Espanol" => "Quitar Todas las Cintas"},
    :change_ot_name => {"English" => "Change OT Name", "Portugues" => "Mudar Nome do OT", "Espanol" => "Cambiar Nombre del OT"},
    :toggle_cannot_store => {"English" => "Toggle Cannot Store", "Portugues" => "Alternar Nao Pode Guardar", "Espanol" => "Alternar No se Puede Guardar"},
    :toggle_cannot_release => {"English" => "Toggle Cannot Release", "Portugues" => "Alternar Nao Pode Soltar", "Espanol" => "Alternar No se Puede Liberar"},
    :toggle_cannot_trade => {"English" => "Toggle Cannot Trade", "Portugues" => "Alternar Nao Pode Trocar", "Espanol" => "Alternar No se Puede Intercambiar"},
    :make_egg => {"English" => "Make Egg", "Portugues" => "Transformar em Ovo", "Espanol" => "Convertir en Huevo"},
    :hatch_egg => {"English" => "Hatch Egg", "Portugues" => "Chocar Ovo", "Espanol" => "Eclosionar Huevo"},
    :one_step_hatch => {"English" => "1 Step to Hatch", "Portugues" => "1 Passo para Chocar", "Espanol" => "1 Paso para Eclosionar"}
  }

